paas_space                    = "get-into-teaching-test"
paas_adviser_application_name = "get-teacher-training-adviser-service-ur"
paas_adviser_route_name       = "get-teacher-training-adviser-service-ur"
paas_linked_services          = ["get-into-teaching-test-redis-svc", "get-into-teaching-api-test-pg-common-svc"]
logging                       = 0
basic_auth                    = 0
alerts                        = {}
azure_key_vault               = "s146t01-kv"
azure_resource_group          = "s146t01-rg"
